config/routes.rb
Qualoo::Application.routes.draw do
  
  CRUD = [:show, :edit, :update, :destroy];
  
  root :to => "pages#presentation";
  
  resources :consumer_salesperson_relationships, :guests;  

  resources :tags do
    resources :consumer_salesperson_relationships, except: CRUD;
  end
  
  resources :messages do
    collection do
      get "search";
      get "sent";
      get "received";
    end
  end
  
  match "inbox" => "messages#received", :as => :inbox;
  
  resources :companies do
    get "search", on: :collection;
  end
  
  resources :categories do
    get "search", on: :collection;
  end
  
  resources :users do
    get "search", on: :collection;
  end
  
  resources :locations do
    post "search", on: :collection;
  end
  
  resources :salespeople do
    resources :consumers, except: CRUD;
    resource :measurement;
    get "search", on: :collection;
  end
  
  resources :posts do
    resource :like;
  end
  
  resources :consumers do
    resources :salespeople, except: CRUD;
    get "search", on: :collection;    
  end;
  
  resource :session, :search, :avatar;
  
  match "login" => "sessions#new", :as => :login;
  match "logout" => "sessions#destroy", :as => :logout;
  match "page/:action", :controller => "pages", :as => :page;
  

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
  include ChildBehavior;
  include Profile;
  
  has_one :location, as: :localizable, dependent: :destroy;
  is_one :user, as: :profile;
  has_many :consumer_salesperson_relationships, conditions: {owner_type: "Consumer"};
  has_many :salespeople, through: :consumer_salesperson_relationships;

  def relates_with
    "Salesperson"
  end
  
  def relates_with?(salesperson)
    salespeople.include?(salesperson.try(:profile));
  end
  
  def network
    relationships.select(&:public?).map(&:salesperson);
  end
  
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  requires_authentication only: :manage;
  before_filter :check_manage, only: [:index];
  
  def search
    @users = Consumer.search(params[:query]);
    title "Pesquisa de #{friendly_profile_name(:consumer, plural: true).downcase} por \"#{params[:query]}\"", :freeze => true;
    render "users/index";
  end
  
  def manage
    @relationships = current_profile.relationships;
  end 
  
  def index  
    @users = Consumer.all;
    title friendly_profile_name(:consumer, plural: true), :freeze => true;
    render "users/index";
  end
  
  def show
    @consumer = Consumer.find(params[:id]);
  end
  
  def new
    welcome_user;
  end
  
  protected
  def check_manage
    if params[:salesperson_id]
      manage;
      render :action => :manage;
      false;
    else true; end
  end
    
  
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_actions.html.erb
<% before_flash do %>
	<% if logged_in? %>
		<p class="title-actions">&nbsp;
			<% if current_user.can_relate_with?(profile) and not current_profile.relates_with?(profile)  %>
				<%= icon "group_add" %> 
				<% add_msg = (current_user.salesperson?) ? "Torna-lo meu cliente" : "Adicionar a minha rede" %>
				<%= link_to add_msg, 
				    new_consumer_salesperson_relationship_path(:id => profile) %>
			<% elsif current_user.can_relate_with?(profile) %>
				<%= icon "delete" %>
				<%= link_to "Excluir da minha rede", consumer_salesperson_relationship_path(current_profile.relationship_with(profile)), 
			     	:confirm => "#{profile.name} sera removido(a) de sua rede?", :method => :delete %>	 
			<% end %>
		</p>
	<% end %>
<% end %>

app/views/consumers/manage.html.erb
<% title "Meus clientes" %>
<%= render :partial => "salespeople/relationships", :locals => {relationships: @relationships, tags_manager: true} %>
<p><%= icon "group_add" %> <%= link_to "Escolha um cliente", consumers_path %> para torna-lo <u>seu</u> cliente.</p>

app/views/consumers/show.html.erb
<% title @consumer.name %>
<% sidebar do %>
	<%= profile_picture(@consumer) %>
	<p>
		<%= icon "email" %> <%= mail_to @consumer.email %><br />
		<%= user_icon @consumer %> <%= friendly_profile_name @consumer %>
	</p>
<% end %>

<%= render "actions", profile: @consumer %>

<% if @consumer.location? %>
	<%= map(@consumer.location) %>
<% end %>

<% if @consumer.network.any? %>
	<h3>Rede de negócios</h3>
	<%= render :partial => "users/list", :locals => {users: @consumer.network, id: "salespeople"} %>
<% end %>