config/routes.rb
Qualoo::Application.routes.draw do
  
  CRUD = [:show, :edit, :update, :destroy];
  
  root :to => "pages#presentation";
  
  resources :consumer_salesperson_relationships, :guests;  

  resources :tags do
    resources :consumer_salesperson_relationships, except: CRUD;
  end
  
  resources :messages do
    collection do
      get "search";
      get "sent";
      get "received";
    end
  end
  
  match "inbox" => "messages#received", :as => :inbox;
  
  resources :companies do
    get "search", on: :collection;
  end
  
  resources :categories do
    get "search", on: :collection;
  end
  
  resources :users do
    get "search", on: :collection;
  end
  
  resources :locations do
    post "search", on: :collection;
  end
  
  resources :salespeople do
    resources :consumers, except: CRUD;
    resource :measurement;
    get "search", on: :collection;
  end
  
  resources :posts do
    resource :like;
  end
  
  resources :consumers do
    resources :salespeople, except: CRUD;
    get "search", on: :collection;    
  end;
  
  resource :session, :search, :avatar;
  
  match "login" => "sessions#new", :as => :login;
  match "logout" => "sessions#destroy", :as => :logout;
  match "page/:action", :controller => "pages", :as => :page;
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :companies;
  
  validates_presence_of :name;
  
  def self.search(query)
    where(["name LIKE ?", "%#{query}%"]);    
  end
  
end

app/models/user.rb
require "digest";

class User < ActiveRecord::Base
  include ParentBehavior;  

  parent_of :profile;
  has_many :sent_messages, order: "created_at DESC", class_name: "Message", foreign_key: :sender_id;
  has_many :received_messages, order: "created_at DESC", class_name: "Message", foreign_key: :recipient_id;
  has_many :measurements_done, class_name: "Measurement", foreign_key: :measurer_id;
  has_many :likes;
  has_many :tags;
  has_one :avatar, class_name: "Image", as: :imageable, dependent: :destroy;
  
  attr_accessor :password;
  
  validates_presence_of :profile_type;
  validates :email, presence: true,
                    uniqueness: true,
                    format: {with: /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i};
  validates :password, presence: true,
                      confirmation: true,
                      if: :password_validation_needed?;
  validates :first_name, presence: true;
  
  before_save :set_profile, :encrypt_new_password;
  after_validation :set_password_confirmation_error;
  after_initialize :default_values;
  
  scope :salespeople, where(profile_type: "Salesperson");
  scope :consumers, where(profile_type: "Consumer");
  
  def self.search(query)
    where([
      "first_name LIKE :query OR last_name LIKE :query", 
      {query: "%#{query}%"}
    ]); 
  end
  
  def self.find_by_profile(profile_type)
    profile_type = profile_type.to_s.classify;
    return all unless profile_type?(profile_type);
    where(profile_type: profile_type);
  end
  
  def self.profile_types
    ["Consumer", "Salesperson"];
  end
  
  def self.profile_type?(profile_type)
    return false unless profile_type;
    profile_types.include?(profile_type.to_s.classify);
  end
  
  def self.authenticate(email, password);
    user = User.find_by_email(email);
    return (user and user.authentic?(password)) ? user : nil;
  end  
  
  def messages(type=nil)
    #(sent_messages + received_messages).sort_by(&:created_at).reverse;
    if type and type.to_sym == :receveid then received_messages;
    elsif type and type.to_sym == :sent then sent_messages;
    else Message.from(self); end
  end
  
  def unread_messages
    received_messages.where(:read => false);
  end
  
  def can_relate_with?(user)
    profile and profile_type == user.profile.relates_with;
  end
  
  def name
    (first_name and last_name) ? "#{first_name} #{last_name}" : first_name;
  end
   
  def profile?(type)
    (profile or (new_record? and profile_type)) ? (profile_type.downcase == type.to_s.downcase) : nil;
  end 
   
  def authentic?(password)
    password_hash == encrypt(password);
  end
  
  def consumer?; profile?(:consumer); end
  def salesperson?; profile?(:salesperson); end
  
  # Implement something else!
  def admin?
    ["bermonruf@gmail.com", "rodolfo.pinotti@gmail.com"].include?(email);
  end
  
  def default_avatar
    self.avatar.destroy;
    self.avatar = nil;
    self.reload;    
  end
  
  protected  
  def default_values
    self.avatar = Image.default(:avatar) if avatar.nil?;
  end
  
  def set_profile
    if new_record? and not profile
      self.profile = profile_type.classify.constantize.create({});
    end
  end
  
  def encrypt_new_password
    self.password_hash = encrypt(@password) if @password.present?;  
  end
  
  def encrypt(string)
    Digest::SHA1.hexdigest(string);
  end
  
  def password_validation_needed?
    password_hash.blank? or @password.present?;
  end
  
  def set_password_confirmation_error
    message = "doesn't match confirmation";
    errors.add(:password_confirmation, "does't match") if !errors[:password].nil? and errors[:password].any?
    errors[:password].replace([]) if errors[:password] == [message];
  end
  
end

app/controllers/salespeople_controller.rb
class SalespeopleController < ApplicationController
  requires_authentication only: :manage;
  before_filter :check_manage, only: [:index];
   
  def search
    @users = Salesperson.search(params[:query]);
    title "Pesquisa de #{friendly_profile_name(:salesperson, plural: true).downcase} por \"#{params[:query]}\"", :freeze => true;
    render "users/index";
  end
   
  def manage
    @relationships = current_profile.relationships;
  end 
   
  def index
    @users = Salesperson.all;
    title friendly_profile_name(:salesperson, plural: true), :freeze => true;
    render "users/index";
  end
  
  def show
    @salesperson = Salesperson.find(params[:id]);
  end
  
  def edit
    @salesperson = current_profile;
  end
  
  def new
    flash.now[:info] = "Quase pronto! So falta preencher os dados abaixo."
    edit;
  end
  
  def create
    @salesperson = current_profile;
    if @salesperson.update_attributes(params[:salesperson])
      welcome_user;
    else
      flash[:error] = "Erro ao cadastrar #{friendly_profile_name(:salesperson).downcase}.";
      render :action => :new;
    end
  end
  
  def update
    @salesperson = current_profile;
    if @salesperson.update_attributes(params[:salesperson])
      flash[:notice] = "Dados atualizados com sucesso!";
      redirect_to page_path(:dashboard);
    else
      flash[:error] = "Erro ao atualizar dados.";
      render :action => :edit;
    end
  end
  
  
  protected
  def check_manage
    if params[:consumer_id]
      manage;
      render :action => :manage;
      false;
    else true; end
  end
  
end

app/helpers/salespeople_helper.rb
module SalespeopleHelper
  
  # Assuming a salesperson with rank 0 has no ranking available, avoiding future problems
  def rank_available?(salesperson)
    l = salesperson.rank_level;
    l and l != 0;
  end
  
  def salesperson_form_url
    {
      new_salesperson_path => salespeople_path,
      edit_salesperson_path(params[:id]) => salesperson_path(current_profile)
    }[request.path];
  end
  
  def salesperson_form_method
    {
      new_salesperson_path => :post,
      edit_salesperson_path(params[:id]) => :put
    }[request.path];    
  end
  
end

app/views/salespeople/_form.html.erb
<%= form_for @salesperson, :method => salesperson_form_method, :url => salesperson_form_url do |f| %>

	<%= f.field_set :company_ids, "Represento as marcas: " do %>
		<% for company in Company.all %> 
			<%= label_tag dom_id(company), company.name %>
			<%= check_box_tag "salesperson[company_ids][]", company.id, @salesperson.from?(company),
			    :id => dom_id(company) %>
		<% end %>
	<% end %>
	
	<%= form_actions :submit => submit, :reset => reset %>

<% end %>

app/views/salespeople/_ranking.html.erb
<span id="ranking" class="level<%= salesperson.rank_level %><%= (logged_in?) ? " rankable" : "" %><%= (rank_available?(salesperson)) ? "" : " not-ranked" %>" title="<%= salesperson.ranks.count("", "? pessoa avaliou", "? pessoas avaliaram") %>">
	<% if logged_in? %>
		<% for i in 1..5 %><%= link_to icon((salesperson.ranked?(i, current_user) ? "star_mid" : "star_off"), :class => "level#{i}"), 
		salesperson_measurement_path(salesperson, :level => i), :method => :post %><% end %>
	<% end %>
</span>

app/views/salespeople/_relationships.html.erb
<% if tags_manager and current_profile.tags.any? %>
	<% sidebar do %>
		<% for tag in current_profile.tags %>
			<h2><%= icon "tag_blue" %> <%= tag.name %></h2>
			<% if tag.targets.any? %>
				<%= render :partial => "users/list", :locals => {users: tag.targets} %>
			<% else %>
				<%= icon "page_white_horizontal" %> Tag vazia
			<% end %>
		<% end %>
	<% end %>
<% end %>

<% if tags_manager %>

	<% if current_user.tags.map(&:name).join("").size > 5 * 4 %>
		<% no_sidebar %>
	<% end %>
	
	<div id="tags">
		<p>
		<% for tag in current_user.tags %>
			<%= link_to tag.name, tag_consumer_salesperson_relationships_path(tag) %>
			<%= link_to icon("delete"), tag_path(tag), :method => :delete %>&nbsp;
		<% end %>
		</p>
		<%= form_for Tag.new, :html => {:class => :inline} do |f| %>
			<% if current_user.tags.empty? %>
				<%= f.label :name, "Nova Tag" %>&nbsp;
			<% end %>
			<%= f.text_field :name %>
			<%= submit_tag icon("add") %>
		<% end %>
	</div>

<% end %>

<% if relationships.any? %>
	<table>
		<!--<caption>Rede de negócios</caption>-->
		<thead>
			<tr>
				<th>Nome</th>
				<th>Visibilidade</th>
				<% if current_user.tags.any? %>
					<th>Tags</th>
				<% end %>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<% for r in relationships %>
			<tr>
				<td><%= user_icon r.target %> <%= link_to r.target.name, profile_path(r.target) %></td>
				<td>
					<%= form_for r, :html => {:class => "inline"} do |f|  %>
						<%= f.select :visibility_id, options_for_select(visibilities, r.visibility.id) %>
						<%= submit_tag icon("accept") %>
					<% end %>
				</td>
				<% if current_user.tags.any? %>
					<td>
						<%= form_for r, :html => {:class => "inline"} do |f| %>
							<% for tag in current_user.tags %>			
								<span>
								<%= label_tag dom_id(tag, dom_id(r)), tag.name, :class => :before %>
								<%= check_box_tag "consumer_salesperson_relationship[tag_ids][]" , tag.id,
								    r.tag?(tag), :id => dom_id(tag, dom_id(r)) %>
								</span>
							<% end %>
							<%= submit_tag icon("accept") %>
						<% end %>
					</td>
				<% end %>
				<td class="centralized">
					<%= link_to icon("delete", :alt => "Excluir"), consumer_salesperson_relationship_path(r), 
				        :confirm => "#{r.target.name} sera removido(a) de sua rede.", :method => :delete %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p><%= icon "page_white_horizontal" %> 
	<%= empty_message rescue "Sua rede ainda esta vazia" %></p>
<% end %>

app/views/salespeople/edit.html.erb
<% title "Dados de #{friendly_profile_name(:salesperson).downcase}" %>
<%= render "form", submit: "Atualizar", reset: "Dados originais" %>

app/views/salespeople/manage.html.erb
<% title "Minha rede de negocios" %>
<%= render "relationships", relationships: @relationships, tags_manager: true %>
<p><%= icon "group_add" %> <%= link_to "Escolha um #{friendly_profile_name(:salesperson).downcase}", salespeople_path %> para adicioná-lo a sua rede.</p>

app/views/salespeople/new.html.erb
<% title "Cadastro" %>
<%= render "form", submit: "Cadastrar", reset: nil %>

app/views/salespeople/show.html.erb
<% title @salesperson.name %>
<% sidebar do %>
	<%= profile_picture(@salesperson) %>
	<p>
		<%= icon "email" %> <%= mail_to @salesperson.email %><br />
		<%= user_icon @salesperson %> <%= friendly_profile_name @salesperson %>
		<%= render "ranking", salesperson: @salesperson %><br />
	</p>
	<ul>
		<% for company in @salesperson.companies %>
			<li><%= icon "shield" %> <%= link_to company.name, company_path(company) %></li>
		<% end %>
	</ul>
<% end %>

<%= render :partial => "consumers/actions", :locals => {profile: @salesperson} %>

<% if @salesperson.location? %>
	<%= map(@salesperson.location) %>
<% end %>


<% if @salesperson.custumers.any? %>
	<h3>Clientes</h3>
	<%= render :partial => "users/list", :locals => {users: @salesperson.custumers, id: "consumers"} %>
<% end %>

<% if @salesperson.posts.any? %>
	<h3>Mural</h3>
	<% if current_user?(@salesperson) %>
		<%= render :partial => "posts/form" %>
	<% end %>
	<%= render :partial => "posts/list", :locals => {posts: @salesperson.posts} %>
<% elsif current_user?(@salesperson) %>
	<h3>Mural</h3>
	<p>Você não tem posts. Crie um abaixo:</p>
	<%= render :partial => "posts/form" %>
	<p class="clear"></p>
<% end %>