config/routes.rb
Qualoo::Application.routes.draw do
  
  CRUD = [:show, :edit, :update, :destroy];
  
  root :to => "pages#presentation";
  
  resources :consumer_salesperson_relationships, :guests;  

  resources :tags do
    resources :consumer_salesperson_relationships, except: CRUD;
  end
  
  resources :messages do
    collection do
      get "search";
      get "sent";
      get "received";
    end
  end
  
  match "inbox" => "messages#received", :as => :inbox;
  
  resources :companies do
    get "search", on: :collection;
  end
  
  resources :categories do
    get "search", on: :collection;
  end
  
  resources :users do
    get "search", on: :collection;
  end
  
  resources :locations do
    post "search", on: :collection;
  end
  
  resources :salespeople do
    resources :consumers, except: CRUD;
    resource :measurement;
    get "search", on: :collection;
  end
  
  resources :posts do
    resource :like;
  end
  
  resources :consumers do
    resources :salespeople, except: CRUD;
    get "search", on: :collection;    
  end;
  
  resource :session, :search, :avatar;
  
  match "login" => "sessions#new", :as => :login;
  match "logout" => "sessions#destroy", :as => :logout;
  match "page/:action", :controller => "pages", :as => :page;
  

end

app/views/pages/dashboard/consumer.html.erb
<ul id="consumer-actions">
	<li><%= icon "group_edit" %> <%= link_to "Gerenciar rede de negocios", manage_relationships_path %></li>
</ul>

app/views/pages/dashboard/salesperson.html.erb
<ul id="salesperson-actions">
	<li><%= icon "group_edit" %> <%= link_to "Gerenciar clientes", manage_relationships_path %></li>
	<li><%= user_icon current_profile %> <%= link_to "Editar dados profissionais", edit_salesperson_path(current_profile) %>
	<li><%= icon "note_edit" %> <%= link_to "Postar no perfil", salesperson_path(current_profile) %></li>
</ul>