config/routes.rb
Qualoo::Application.routes.draw do
  
  CRUD = [:show, :edit, :update, :destroy];
  
  root :to => "pages#presentation";
  
  resources :consumer_salesperson_relationships, :guests;  

  resources :tags do
    resources :consumer_salesperson_relationships, except: CRUD;
  end
  
  resources :messages do
    collection do
      get "search";
      get "sent";
      get "received";
    end
  end
  
  match "inbox" => "messages#received", :as => :inbox;
  
  resources :companies do
    get "search", on: :collection;
  end
  
  resources :categories do
    get "search", on: :collection;
  end
  
  resources :users do
    get "search", on: :collection;
  end
  
  resources :locations do
    post "search", on: :collection;
  end
  
  resources :salespeople do
    resources :consumers, except: CRUD;
    resource :measurement;
    get "search", on: :collection;
  end
  
  resources :posts do
    resource :like;
  end
  
  resources :consumers do
    resources :salespeople, except: CRUD;
    get "search", on: :collection;    
  end;
  
  resource :session, :search, :avatar;
  
  match "login" => "sessions#new", :as => :login;
  match "logout" => "sessions#destroy", :as => :logout;
  match "page/:action", :controller => "pages", :as => :page;
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :salesperson;
  has_many :likes;  
  
  validates_presence_of :salesperson, :body;
  
  def nlikes
    likes.size;
  end
  
  def users_liked
    likes.map(&:user);
  end
  
  def like(user)
    likes.find_or_create_by_user_id(user.id);
  end
  
  def unlike(user)
    like(user).destroy if liked?(user);
  end
  
  def liked?(user)
    !!likes.find_by_user_id(user.id);
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  requires_authentication user: :salesperson;

  def create
    @post = current_profile.posts.new(params[:post]);
    if @post.save
      flash[:notice] = "Post criado com sucesso!";
      redirect_to salesperson_path(current_profile);
    else
      flash[:error] = "Post vazio!";
      redirect_to :back;
    end
  end
  
  def destroy
    @post = current_profile.posts.find(params[:id]);
    @post.destroy;
    flash[:info] = "Post deletado.";
    redirect_to salesperson_path(current_profile);
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_tag posts_path, :class => "embed", :id => "new-post" do %>

	<%= text_area :post, :body, :rows => 2 %>
	<p class="actions"><%= submit_tag icon("note_edit") %></p>
	
<% end %>

app/views/posts/_list.html.erb
<div id="posts">
	<% for post in posts %>
		<div class="post">
			<p class="body"><%= icon "note" %> <%= post.body %></p>
			<p class="meta">
				<%= post.nlikes.count "", "? ", "? " %> 
				<% if logged_in? and post.liked?(current_user) %>
					<%= icon "thumb_down" %> <%= link_to "Descurtir", post_like_path(post), :method => :delete %> 
				<% elsif logged_in? %>
					<%= icon "thumb_up" %> <%= link_to "Curtir", post_like_path(post), :method => :post %> 
				<% else %>
					<%= post.nlikes.count "", "pessoa curtiu", "pessoas curtiram" %>
				<% end %>
				<% if current_user?(post.salesperson) %>
					&nbsp;<%= link_to icon("delete") + " Deletar", post_path(post),
					 	:confirm => "O post sera deletado.", :method => :delete %>
				<% end %>
			</p>
			<p class="time">
				<%= time_ago_in_words(post.created_at) %>
			</p>
		</div>
	<% end %>
</div>